Enable Clang/LLVM builds for Qt 6.7+ on Windows
Note, requires skipping the StatusService::serviceDiscovered()
test, due to LLVM/Clang bug [#110975](
https://github.com/llvm/llvm-project/issues/110975).

Squashed commit of the following:

commit 5f78eb41bcd93aa469619f6cefe8e79ccca4e603
Author: Paul Colby <git@colby.id.au>
Date:   Wed Jan 8 17:36:09 2025 +1100

    Restore all remaining (Linux and macOS) builds

commit 347614749f828174b0e5f3e445197d9f3d764394
Author: Paul Colby <git@colby.id.au>
Date:   Wed Jan 8 17:22:18 2025 +1100

    Restore all other Windows builds

commit c3ea43b532437f4bdecb559f6b298fd87594a954
Author: Paul Colby <git@colby.id.au>
Date:   Wed Jan 8 17:06:45 2025 +1100

    Restore the msvc and mingw builds

commit c4492d688b5f0d692eb42f181f0d05c228b363e2
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 23:22:15 2025 +1100

    Don't include compiler runtime for llvm-mingw

    Not supported by windeployqt.

commit b1e47900e541bb264cd889a79652d4d4a47198c7
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 23:18:28 2025 +1100

    Skip test collation for LLVM builds on Windows

    No sure why, but lcov fails in this scenario, at least on GitHub
    hosted runners:

    > error: Failed to load coverage: 'D:/a/_temp/coverage/src/lib/
    > CMakeFiles/QtPokit.dir/QtPokit_autogen/mocs_compilation.cpp.obj':
    > Malformed coverage data
    > error: Could not load coverage information

commit 776df94eee15b5aee603dc7b1fac6913ae6f64fd
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 23:18:17 2025 +1100

    Skip StatusService::serviceDiscovered test on llvm-mingw

    Thanks to LLVM/Clang bug [#110975](
    https://github.com/llvm/llvm-project/issues/110975).

commit 78812f68242e79a0f6f9be057da703c1a6c3bcb9
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 23:16:16 2025 +1100

    Test StatusService with text output

commit 1ae1534ae7a91af1bb66d0a74bb2d2e9f6012105
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 23:14:53 2025 +1100

    Restore the simplied workflow syntax

    Since the previous commit fixed it.

commit fa85c4088a4949ac21c4e9e9038ea793abf5ccd7
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 23:13:15 2025 +1100

    Don't exclude Window LLVM builds for Qt 6.7+

commit 5240903151a118e404f8962eed5afde71934a34a
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 22:51:45 2025 +1100

    Add LLVM test debugging

    That is, merge the TestStatusService tests from the
    install-qt-action-4.1.0 branch (which is just much, much easier
    than trying to merge main into that branch now).

commit d662b43ed659db30d0820417f5ee0d0ea34630a6
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 22:35:59 2025 +1100

    Set aqtTools the redundant way for now

commit ecf4b20301730ad3877ac4c0866fe2e09f6a6c4b
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 22:33:56 2025 +1100

    Include the Qt-supplied llvm-mingw tool/s

commit 4b98d52db8107d6c86a2329fd77191f2c8875b9b
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 22:24:25 2025 +1100

    Set the generator manually for now

    Not sure why the existing syntax isn't working.

commit 2ba9025f281028be492ec73931eb67fb035c5670
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 22:09:27 2025 +1100

    Try the Qt 6.7+ LLVM builds on Windows