Bump Doxygen to v1.18.0
Squashed commit of the following:

commit 072a87e320048fec114c43779bdc25be5ea156b9
Author: Paul Colby <git@colby.id.au>
Date:   Fri Aug 14 12:54:18 2026 +1000

    Bump Doxygen to v1.18.0

    Doxygen v1.18.0 has resolved the ScanCommand / Qt tags issue introduced
    in v1.17.0.

    See https://github.com/doxygen/doxygen/issues/12256
    See https://www.doxygen.nl/manual/changelog.html#log_1_18_0

commit c084700b687f409b5d7388fe15d052b2bc1512d0
Merge: c9fb147f6 1da17bf4d
Author: Paul Colby <git@colby.id.au>
Date:   Fri Aug 14 12:49:07 2026 +1000

    Merge branch 'main' into doxygen-1.17.0

commit c9fb147f6829c36641a34443d6e3f1e53bd86636
Merge: babb081b1 ef0874f6b
Author: Paul Colby <git@colby.id.au>
Date:   Sun Jul 26 16:44:55 2026 +1000

    Merge branch 'main' into doxygen-1.17.0

commit babb081b105c475d0d9408a0e56df0a4f3b26ba9
Author: Paul Colby <git@colby.id.au>
Date:   Fri May 1 14:19:48 2026 +1000

    Bump Doxygen to v1.17.0

    Note, this currently results in the following Doxygen warning (which we
    treat as an error):

    > dokit/src/cli/scancommand.h:35: error: Member toJson(const
    > QBluetoothDeviceInfo::ServiceClasses &classes) (function) of class
    > ScanCommand is not documented.

    However, this appears to be untrue / a Doxygen bug. More investigation
    will be required.